olliecase-green/KnowledgeChecklistFrontend

knowledge-challenge-app/Components/Dashboard/Dashboard.js, knowledge-challenge-app/Components/LO/LO.js, knowledge-challenge-app/Components/Networking.js, knowledge-challenge-app/Components/Topic/Topic.js, knowledge-challenge-app/Components/confidenceButton/confidenceButton.js
Made some components folders with blank test files
=> creating dashboard skeleton

knowledge-challenge-app/src/App.js, knowledge-challenge-app/src/Components/Header.js, knowledge-challenge-app/src/Components/Homepage.js, knowledge-challenge-app/src/Components/header.css
=> Styled website

knowledge-challenge-app/package-lock.json, knowledge-challenge-app/package.json, knowledge-challenge-app/src/App.css, knowledge-challenge-app/src/Components/LO/LO.css, knowledge-challenge-app/src/Components/LO/LO.js, knowledge-challenge-app/src/Components/StudentDashboard/StudentDashboard.css, knowledge-challenge-app/src/Components/StudentDashboard/StudentDashboard.js, knowledge-challenge-app/src/Components/confidenceButton/confidenceButton.js, knowledge-challenge-app/yarn.lock
Student dashboard looks more complete. Sidenav needs adjusting. More CSS applied.
=> Continue dashboard

knowledge-challenge-app/package-lock.json, knowledge-challenge-app/src/Components/LO/LO.css, knowledge-challenge-app/src/Components/LO/LO.js, knowledge-challenge-app/src/Components/SignupModal.js, knowledge-challenge-app/src/Components/StudentDashboard/StudentDashboard.js, knowledge-challenge-app/yarn.lock
=> Merging colour change across to main

knowledge-challenge-app/src/App.js, knowledge-challenge-app/src/Components/Header.js, knowledge-challenge-app/src/Components/StudentDashboard/StudentDashboard.js
updated cookies to show current email and user_id. The props can then be used for customisation.
=> Fixed header to show correct person

knowledge-challenge-app/src/App.js, knowledge-challenge-app/src/Components/AdminDashboard.js, knowledge-challenge-app/src/Components/Networking.js, knowledge-challenge-app/src/Components/StudentDashboard/StudentDashboard.js
Working admin page generated upon admin login however the page needs refreshing to work - needs investigating
=> Added admin functionality - needs refresh to work

knowledge-challenge-app/src/Components/AdminDashboard/AdminDashboard.js, knowledge-challenge-app/src/Components/Homepage.js, knowledge-challenge-app/src/Components/Networking.js
When clicking a cohort button, the cohort LOs are logged to the console
=> Made buttons which select cohort LOs

knowledge-challenge-app/src/App.js, knowledge-challenge-app/src/Components/AdminDashboard/AdminDashboard.js, knowledge-challenge-app/src/Components/AdminDashboard/ViewData.js
still needs to render in the relevant data.
=> added redirection for when cohort is chosen

knowledge-challenge-app/package-lock.json, knowledge-challenge-app/src/App.js, knowledge-challenge-app/src/Components/AdminDashboard/AdminDashboard.js, knowledge-challenge-app/src/Components/AdminDashboard/ViewData.js, knowledge-challenge-app/src/Components/AdminDashboard/ViewResult.js, knowledge-challenge-app/src/Components/AdminDashboard/view-result.css, knowledge-challenge-app/src/Components/Networking.js
made new component so admin can view the result for all users.
=> admin can now see results for all users

knowledge-challenge-app/package-lock.json, knowledge-challenge-app/src/App.js, knowledge-challenge-app/src/Components/AdminDashboard/AdminDashboard.js, knowledge-challenge-app/src/Components/AdminDashboard/ViewData.js, knowledge-challenge-app/src/Components/Networking.js
Needs to be rendered after clicking the button
=> Added insert LO button functionality

knowledge-challenge-app/src/App.js, knowledge-challenge-app/src/Components/AdminDashboard/AdminDashboard.js, knowledge-challenge-app/src/Components/AdminDashboard/ViewData.js, knowledge-challenge-app/src/Components/AdminDashboard/ViewResult.js, knowledge-challenge-app/src/Components/AdminDashboard/view-result.css, knowledge-challenge-app/src/Components/Networking.js
added rendering when score changes, the background colour changes as well. If learning objected added, this is also added to all students and the page gets updates as well.
=> Added conditional rendering depending on score

.gitignore, knowledge-challenge-app/src/App.js, knowledge-challenge-app/src/Components/LO/LO.css, knowledge-challenge-app/src/Components/LO/LO.js, knowledge-challenge-app/src/Components/Networking.js, knowledge-challenge-app/src/Components/StudentDashboard/StudentDashboard.js, knowledge-challenge-app/src/Components/confidenceButton/confidenceButton.js
Added fixes to the progress bar. 
POST request fires properly on button click to update frontend and backend. 
Need log-in to render updated state.
=> Number of Changes to StudentDashboard

knowledge-challenge-app/src/Components/AdminDashboard/ViewData.js, knowledge-challenge-app/src/Components/AdminDashboard/ViewResult.js, knowledge-challenge-app/src/Components/AdminDashboard/view-result.css
Student results is now consistent in appearance with the rest of the admin pages
=> Added student name to results and made it card

knowledge-challenge-app/src/Components/AdminDashboard/AddLOModal.js, knowledge-challenge-app/src/Components/AdminDashboard/ViewData.js, knowledge-challenge-app/src/Components/AdminDashboard/view-result.css, knowledge-challenge-app/src/Components/Networking.js
can now delete specific learning objectives for specific cohorts.
=> Added delete feature

knowledge-challenge-app/src/Components/AdminDashboard/AdminDashboard.js, knowledge-challenge-app/src/Components/AdminDashboard/ViewData.js, knowledge-challenge-app/src/Components/Networking.js, knowledge-challenge-app/src/Components/StudentDashboard/StudentDashboard.css
=> Added create cohort button

knowledge-challenge-app/src/Components/LogInModal.js, knowledge-challenge-app/src/Components/SignupModal.js
Log in and register buttons updated
=> Changed button styling to be consistent

LICENSE.md, README.md
=> Started writing frontend documentation.

README.md, knowledge-challenge-app/src/Components/StudentDashboard/StudentDashboard.js, knowledge-challenge-app/src/Components/StudentDashboard/__test__/StudentDashboard.test.js, knowledge-challenge-app/src/Components/confidenceButton/__test__/confidenceButton.test.js
Started writing basic unit tests.
=> Writing tests

knowledge-challenge-app/src/App.test.js, knowledge-challenge-app/src/Components/AdminDashboard/AdminDashboard.js, knowledge-challenge-app/src/Components/AdminDashboard/__test__/AdminDashboard.test.js, knowledge-challenge-app/src/Components/Footer.js, knowledge-challenge-app/src/Components/Header.js, knowledge-challenge-app/src/Components/LO/LO.css, knowledge-challenge-app/src/Components/LO/LO.js, knowledge-challenge-app/src/Components/LO/__test__/LO.test.js, knowledge-challenge-app/src/Components/SignupModal.js, knowledge-challenge-app/src/Components/SignupModal/__test__/SignupModal.test.js, knowledge-challenge-app/src/Components/StudentDashboard/StudentDashboard.css, knowledge-challenge-app/src/Components/StudentDashboard/StudentDashboard.js, knowledge-challenge-app/src/Components/StudentDashboard/__test__/StudentDashboard.test.js, knowledge-challenge-app/src/Components/confidenceButton/__test__/confidenceButton.test.js, knowledge-challenge-app/yarn.lock
Tests for Student Dashboard, LOs and Register form.
=> Written a lot more tests. Tests for some components remaining.

knowledge-challenge-app/public/index.html, knowledge-challenge-app/src/App.js, knowledge-challenge-app/src/Components/AdminDashboard/AddLOModal.js, knowledge-challenge-app/src/Components/AdminDashboard/AdminDashboard.js, knowledge-challenge-app/src/Components/Header.js, knowledge-challenge-app/src/Components/LO/LO.js, knowledge-challenge-app/src/Components/LogInModal.js, knowledge-challenge-app/src/Components/SignupModal.js, knowledge-challenge-app/src/Components/StudentDashboard/StudentDashboard.js
removed unused variables, fixed major bug in progress bar, now correctly updates and  and added dashboard link in admin header.
=>  fixed major bug in progress bar
